<<setup, include=FALSE>>=
knitr::opts_template$set(
  fig.wide = list(fig.height = 4, fig.width = 7),
  fig.norm = list(fig.height = 7, fig.width = 7)
)

library(lattice)
library(dplyr)
library(tidyr)
library(corrgram)

# import the specified dataset
library(lb, character.only = TRUE)
df <- get(ds)

# customisation hooks
basic_hists <- TRUE
basic_bwplots <- TRUE
basic_splom <- TRUE
basic_corrgram <- TRUE
basic_ttests <- TRUE
@